controller_manager:
  ros__parameters:
    update_rate: 100  # H

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory:
      type: joint_trajectory_controller/JointTrajectoryController
      
    gripper_control:
      type: forward_command_controller/ForwardCommandController
    #  type: position_controllers/JointGroupPositionController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

joint_trajectory:
  ros__parameters:
    joints:
      - arm_base_joint
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - gripper_base_joint
      # ...

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

gripper_control:
  ros__parameters:
    joints:
      - gripper_finger_left_joint

    
    

    interface_name: position

# effort_control:
#   ros__parameters:
#     joints:
#       - gripper_finger_left_joint

#     state_interfaces:
#       - effort

    # command_interfaces:
    #   - effort

    # state_interfaces:
    #   - position
    #   - velocity